### ISSUE TITLE
何时实现多驱动

### ISSUE THREAD

**Issue by byteferry** [RunnerLee/queue#10]
我们想要支持  kafak  rabitmq, gearman ......

**Comment by RunnerLee** [comment]
嗯.. 推荐改用这个包:

https://github.com/wangsir0624/queue

一个朋友做的, 比我这个更好

**Comment by byteferry** [comment]
那是数据传递方式的，效率仍是上不来。我说的多驱动则是kafak rabitmq, gearman, beanstalk这样的消息队列。而不是数据队列。不过，还是谢谢你。
